version: "3"
services:
  proxy:
    image: harbor.tomsk-it.ru/dockerhub/bitnami/nginx:1.25.1-debian-11-r2
    container_name: shared-proxy
    ports:
      - 80:8080
      - 443:4443
    volumes:
      - ./tls:/tmp/tls
      - ./server_blocks/:/opt/bitnami/nginx/conf/server_blocks/
    networks:
      - server
networks:
  server:
    external: true